tasks:
  - name: Docker and Composer setup
    init: |
      docker-compose up -d
      composer install
    command: |
      docker-compose exec web php bin/console doctrine:migrations:migrate --no-interaction
